# Site settings
title: "TheBlog of TheGetch"
email: your-email@example.com
description: "Just another blog about Penetration Testing."
baseurl: ""
url: "https://thegetch.github.io/"
title_description: ""
title_image: "https://thegetch.github.io/images/ster.jpg"
github_repository: https://github.com/TheGetch
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: _TheGetch_
github_username:  TheGetch
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/ericgetchell/
google_plus_link: 
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: "&copy; 2021 TheGetch with Jekyll."

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
